#!/bin/bash

device="{query}"

if [[ $query =~ (input) ]]; then
  type=input
else
  type=output
fi

if [ -x /usr/local/bin/SwitchAudioSource ]; then
  /usr/local/bin/SwitchAudioSource -t $type -s "$device"
elif [ -x "$(which SwitchAudioSource)" ]; then
  SwitchAudioSource -t $type -s "$device"
fi
